name: unit-tests
on: [push]
jobs:
  start:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, bootstrap, lint and test
        run: |
          npm i
          npm run bootstrap
#          npm run lint
          npm run test
        env:
          CI: true
